### ISSUE TITLE
Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable

### ISSUE THREAD

**Issue by morrislaptop** [gh640/phpunit-tap#5]
I get this error when running tests instead of the actual exception occurring. 

If I run without using this reporter, then I get a better description of the exception. 

Is there anyway to prevent this?

**Comment by gh640** [comment]
Thank you for sharing the issue.

Hmm. I'm sorry, I have no idea only with the information... If you would share more detailed information to reproduce the error, I may help.

Or, the error seems reported in many issue queues and forums and it may be worth seeing pages like the followings:

- https://github.com/laravel/framework/issues/10808
- https://stackoverflow.com/questions/41304663/target-illuminate-contracts-debug-exceptionhandler-is-not-instantiable
- https://laracasts.com/discuss/channels/testing/phpunit-exceptionhandler-is-not-instantiable

**Comment by morrislaptop** [comment]
Hi @gh640 ,

I've made a demo repo at https://github.com/morrislaptop/laravel-tap-5

```
➜  laravel-tap-5 (master) ✔ vendor/bin/phpunit
PHPUnit 7.2.7 by Sebastian Bergmann and contributors.

.E                                                                  2 / 2 (100%)

Time: 89 ms, Memory: 12.00MB

There was 1 error:

1) Tests\Feature\ExampleTest::testBasicTest
Exception: This is an exception

/Users/craigmorris/Dev/laravel-tap-5/tests/Feature/ExampleTest.php:19

ERRORS!
Tests: 2, Assertions: 1, Errors: 1.
➜  laravel-tap-5 (master) ✔ vendor/bin/phpunit --printer gh640\\PhpunitTap\\TapResultPrinter
TAP version 13
PHPUnit 7.2.7 by Sebastian Bergmann and contributors.

ok 1 - Tests\Unit\ExampleTest::testBasicTest
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php:933
Stack trace:
#0 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/craigmorris/Dev/laravel-tap-5/vendor/la in /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 933

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php:933
Stack trace:
#0 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/craigmorris/Dev/laravel-tap-5/vendor/la in /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 933
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php:933
Stack trace:
#0 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/craigmorris/Dev/laravel-tap-5/vendor/la in /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 933

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php:933
Stack trace:
#0 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/craigmorris/Dev/laravel-tap-5/vendor/la in /Users/craigmorris/Dev/laravel-tap-5/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 933
```

**Comment by gh640** [comment]
@morrislaptop thanks. I could reproduce the problem with your demo repo. I investigated and found that `TestUtil::describe($test)` in `writeNotOk()` is the cause.

https://github.com/gh640/phpunit-tap/blob/master/src/TapResultPrinter.php#L213-L230

If I change it to `TestUtil::describeAsString($test)` in my environment, the error disappears and the expected normal report is displayed. Could you try changing that in your environment and let me know the result? I made a branch `5-fix_uncaught_exception` for this change and you can use it. Or, please directly change the line in your `vendor/`.

https://github.com/gh640/phpunit-tap/commit/b8c60396242de5c0859c662720ec894713751aeb#diff-1cda75bf968b9b1c5f3ced2b6571d7ccL225

(Maybe we should have changed it in https://github.com/gh640/phpunit-tap/commit/46d97a66c2b86d53a5d48f7f82528a18468cb03e#diff-1cda75bf968b9b1c5f3ced2b6571d7ccL203 ?)

If it works in your environment, I'll commit the change in `master` branch. Thanks :)

**Comment by morrislaptop** [comment]
This works for me :)

**Comment by gh640** [comment]
Thanks! I've made a new release `3.0.1`.
